---
#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

title: Chemistry Magazine | The Catalyst
logo: /assets/images/logo.png # You can add own logo
description: # Add your awesome description
copyright: The Catalyst
# Preloader
preloader: true # To disable preloader change value to false

menu:
  - name: Home
    url: /
  - name: Issues
    url: /category/issues
    submenu: 
      - name: "Spring (2022)"
        url: /2021-04-24-april-issue-4
      - name: "Winter #2 (2021)"
        url: /2021-01-30-january-issue-3
      - name: "Winter #1 (2021)"
        url: /2021-12-26-december-issue-2
      - name: "Autumn #1 (2021)"
        url: /2021-09-26-september-issue-1
  - name: Recommendations
    url: /contact/
  - name: About Us
    url: /
    submenu: 
      - name: "Meet Our Team"
        url: /meet_the_team
      - name: "About Us"
        url: /issues
      - name: "Join Us"
        url: /issues
      - name: "Contact Us"
        url: /contact
# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

collections:
  teams:
    output: true

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: I’m a Freelance Interactive Art Director based in France. Focusing across branding and identity, digital and print.
  hero-banner: /assets/images/banner-img.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Jhon Abraham

#-------------------------------
# Contact Info
contact:
  email: thecatalyst-magazine@outlook.com
  phone: +90 000 333 22
  address:
    city: London
    street: 6 rip carl Avenue CA 90733

# Contact Form
contact-form: thecatalyst-magazine@outlook.com

# Social links
social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/company/connectingchemists/" }
  - { icon: "ti-instagram", link: "https://www.instagram.com/thecatalyst.magazine/"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: false  # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:path

defaults:
  - scope:
      path: "_posts"
    values:
      permalink: /:path

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
